# Generated by Django 6.0 on 2026-01-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photos',
            new_name='photo',
        ),
    ]
